name = "smart-recipe-planner-app"
compatibility_date = "2024-04-16"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "SESSION"
id = "64e1fa1d17084a5ba4f9e336b1bd9026"
