import type { LocalPlannedMeal } from '@/lib/db';

export type RecommendedMeal = Omit<LocalPlannedMeal, 'id' | 'planId' | 'mealDate' | 'isSynced' | 'isDeleted' | 'isNew'>;

export const RECOMMENDED_WEEKLY_MENU: Record<string, RecommendedMeal[]> = {
    lun: [
        {
            "recipeUUID": "ae12d052-b040-4183-a8d2-60c9a45a14b9",
            "recipeName": "Tortilla Wrap Hack con Huevo y Aguacate",
            "imageUrl": "https://res.cloudinary.com/dcjdxf0kk/image/upload/v1778652475/smart-recipe-planner/ai-generated/viral-egg-and-avocado-tortilla-wrap-hack-1778652475786.jpg",
            "calories": 713,
            "proteinGrams": 28,
            "carbsGrams": 32,
            "fatGrams": 24,
            "mealType": "BREAKFAST",
            "portionMultiplier": 1,
            "selectionLogicCode": "PROTEIN_FILL",
            "aiReasoning": "Ideal para iniciar la semana con grasas saludables y proteínas limpias.",
            "estimatedCost": 45,
            "pantryUsage": 0
        },
        {
            "recipeUUID": "aa3eee83-c5e3-4aaa-b7e0-6d5667b92764",
            "recipeName": "Pechuga de Pollo con Costra de Amaranto y Miel",
            "imageUrl": "https://res.cloudinary.com/dcjdxf0kk/image/upload/v1778569527/smart-recipe-planner/ai-generated/amaranth-and-honey-crusted-chicken-breast-1778569527013.jpg",
            "calories": 756,
            "proteinGrams": 76,
            "carbsGrams": 45,
            "fatGrams": 12,
            "mealType": "LUNCH",
            "portionMultiplier": 0.6,
            "selectionLogicCode": "PROTEIN_FILL",
            "aiReasoning": "Este plato es ideal para mantener tu energía hoy.",
            "estimatedCost": 75,
            "pantryUsage": 0
        },
        {
            "recipeUUID": "d21bbd6e-ad3e-4f85-bbb0-7a973386d2fd",
            "recipeName": "Sopa de pasta integral con verduras en juliana",
            "imageUrl": "https://res.cloudinary.com/dcjdxf0kk/image/upload/v1776924910/smart-recipe-planner/ai-generated/whole-wheat-pasta-soup-with-julienned-vegetables-1776924910828.jpg",
            "calories": 483,
            "proteinGrams": 16,
            "carbsGrams": 55,
            "fatGrams": 8,
            "mealType": "DINNER",
            "portionMultiplier": 1,
            "selectionLogicCode": "PROTEIN_FILL",
            "aiReasoning": "Cena reconfortante y ligera para promover un buen descanso.",
            "estimatedCost": 35,
            "pantryUsage": 0
        },
        {
            "recipeUUID": "0a842844-165a-4953-87e0-2294ebd10b06",
            "recipeName": "Pudín de camote con leche de coco y vainilla",
            "imageUrl": "https://res.cloudinary.com/dcjdxf0kk/image/upload/v1778306770/smart-recipe-planner/ai-generated/sweet-potato-pudding-with-coconut-milk-and-vanilla-1778306770387.jpg",
            "calories": 320,
            "proteinGrams": 5,
            "carbsGrams": 40,
            "fatGrams": 14,
            "mealType": "SNACK",
            "portionMultiplier": 1,
            "selectionLogicCode": "PROTEIN_FILL",
            "aiReasoning": "Energía natural de carbohidratos complejos para media tarde.",
            "estimatedCost": 25,
            "pantryUsage": 0
        },
        {
            "recipeUUID": "f90dd5f9-108e-4296-bf64-ef9157556414",
            "recipeName": "Agua fresca de tamarindo natural sin azúcar",
            "imageUrl": "https://res.cloudinary.com/dcjdxf0kk/image/upload/v1777619350/smart-recipe-planner/ai-generated/natural-sugar-free-tamarind-agua-fresca-1777619350330.jpg",
            "calories": 95,
            "proteinGrams": 1,
            "carbsGrams": 22,
            "fatGrams": 0,
            "mealType": "SNACK",
            "portionMultiplier": 1,
            "selectionLogicCode": "PROTEIN_FILL",
            "aiReasoning": "Bebida fresca y antioxidante sin azúcares añadidos.",
            "estimatedCost": 15,
            "pantryUsage": 0
        }
    ],
    mar: [
        {
            "recipeUUID": "e30e12b7-a3f5-4122-83b9-a9a72199b510",
            "recipeName": "Omelette de Claras con Espinacas y Queso Panela",
            "imageUrl": "https://res.cloudinary.com/dcjdxf0kk/image/upload/v1778652475/smart-recipe-planner/ai-generated/viral-egg-and-avocado-tortilla-wrap-hack-1778652475786.jpg",
            "calories": 310,
            "proteinGrams": 26,
            "carbsGrams": 8,
            "fatGrams": 12,
            "mealType": "BREAKFAST",
            "portionMultiplier": 1,
            "selectionLogicCode": "PROTEIN_FILL",
            "aiReasoning": "Desayuno alto en proteína y muy bajo en calorías para quemar grasa.",
            "estimatedCost": 35,
            "pantryUsage": 0
        },
        {
            "recipeUUID": "33b2fe99-b1d5-47e0-9111-c918ee9f3e33",
            "recipeName": "Salmón al Horno con Limón y Romero",
            "imageUrl": "https://res.cloudinary.com/dcjdxf0kk/image/upload/v1778569527/smart-recipe-planner/ai-generated/amaranth-and-honey-crusted-chicken-breast-1778569527013.jpg",
            "calories": 620,
            "proteinGrams": 42,
            "carbsGrams": 10,
            "fatGrams": 34,
            "mealType": "LUNCH",
            "portionMultiplier": 1,
            "selectionLogicCode": "PROTEIN_FILL",
            "aiReasoning": "Grasas omega-3 y proteínas esenciales de alta biodisponibilidad.",
            "estimatedCost": 110,
            "pantryUsage": 0
        },
        {
            "recipeUUID": "9e2c69d8-c11a-4d22-8d20-1a1a11ee99ff",
            "recipeName": "Crema Ligera de Calabacitas y Cilantro",
            "imageUrl": "https://res.cloudinary.com/dcjdxf0kk/image/upload/v1776924910/smart-recipe-planner/ai-generated/whole-wheat-pasta-soup-with-julienned-vegetables-1776924910828.jpg",
            "calories": 240,
            "proteinGrams": 6,
            "carbsGrams": 20,
            "fatGrams": 10,
            "mealType": "DINNER",
            "portionMultiplier": 1,
            "selectionLogicCode": "PROTEIN_FILL",
            "aiReasoning": "Fácil digestión con micronutrientes esenciales de vegetales verdes.",
            "estimatedCost": 25,
            "pantryUsage": 0
        },
        {
            "recipeUUID": "bc29e1a1-f3d2-4fe1-ba11-3e441ee44211",
            "recipeName": "Avena Reposada con Chía y Almendras",
            "imageUrl": "https://res.cloudinary.com/dcjdxf0kk/image/upload/v1778306770/smart-recipe-planner/ai-generated/sweet-potato-pudding-with-coconut-milk-and-vanilla-1778306770387.jpg",
            "calories": 280,
            "proteinGrams": 10,
            "carbsGrams": 35,
            "fatGrams": 9,
            "mealType": "SNACK",
            "portionMultiplier": 1,
            "selectionLogicCode": "PROTEIN_FILL",
            "aiReasoning": "Fibra soluble para mejorar la digestión y mantener la saciedad.",
            "estimatedCost": 20,
            "pantryUsage": 0
        },
        {
            "recipeUUID": "ad771bc1-332e-4fd1-a8df-2c3e11aa9922",
            "recipeName": "Infusión Fría de Limón, Menta y Jengibre",
            "imageUrl": "https://res.cloudinary.com/dcjdxf0kk/image/upload/v1777619350/smart-recipe-planner/ai-generated/natural-sugar-free-tamarind-agua-fresca-1777619350330.jpg",
            "calories": 15,
            "proteinGrams": 0,
            "carbsGrams": 3,
            "fatGrams": 0,
            "mealType": "SNACK",
            "portionMultiplier": 1,
            "selectionLogicCode": "PROTEIN_FILL",
            "aiReasoning": "Bebida termogénica natural e hidratante.",
            "estimatedCost": 10,
            "pantryUsage": 0
        }
    ],
    mie: [
        {
            "recipeUUID": "ae2211bb-3f2d-411a-8bbd-1e12e3e21a20",
            "recipeName": "Pan Tostado con Aguacate y Semillas de Girasol",
            "imageUrl": "https://res.cloudinary.com/dcjdxf0kk/image/upload/v1778652475/smart-recipe-planner/ai-generated/viral-egg-and-avocado-tortilla-wrap-hack-1778652475786.jpg",
            "calories": 420,
            "proteinGrams": 9,
            "carbsGrams": 38,
            "fatGrams": 18,
            "mealType": "BREAKFAST",
            "portionMultiplier": 1,
            "selectionLogicCode": "PROTEIN_FILL",
            "aiReasoning": "Carbohidratos complejos y grasas monoinsaturadas para iniciar tu miércoles.",
            "estimatedCost": 30,
            "pantryUsage": 0
        },
        {
            "recipeUUID": "ff22dd33-a2b1-4cd2-b912-2c32de11eeff",
            "recipeName": "Tacos de Pechuga al Pastor con Piña Asada",
            "imageUrl": "https://res.cloudinary.com/dcjdxf0kk/image/upload/v1778569527/smart-recipe-planner/ai-generated/amaranth-and-honey-crusted-chicken-breast-1778569527013.jpg",
            "calories": 590,
            "proteinGrams": 48,
            "carbsGrams": 42,
            "fatGrams": 14,
            "mealType": "LUNCH",
            "portionMultiplier": 1,
            "selectionLogicCode": "PROTEIN_FILL",
            "aiReasoning": "Versión saludable de un clásico mexicano con bajo aporte de grasa.",
            "estimatedCost": 60,
            "pantryUsage": 0
        },
        {
            "recipeUUID": "dd11ee99-f2e2-4112-be33-ee3312abef00",
            "recipeName": "Ensalada César Fit con Tiras de Pollo a la Plancha",
            "imageUrl": "https://res.cloudinary.com/dcjdxf0kk/image/upload/v1776924910/smart-recipe-planner/ai-generated/whole-wheat-pasta-soup-with-julienned-vegetables-1776924910828.jpg",
            "calories": 380,
            "proteinGrams": 36,
            "carbsGrams": 12,
            "fatGrams": 18,
            "mealType": "DINNER",
            "portionMultiplier": 1,
            "selectionLogicCode": "PROTEIN_FILL",
            "aiReasoning": "Cena fresca, rica en fibra y con proteínas de excelente absorción.",
            "estimatedCost": 50,
            "pantryUsage": 0
        },
        {
            "recipeUUID": "cc33bb22-e3d1-4112-99ab-ccee2211bb33",
            "recipeName": "Yogur Griego con Frambuesas y Nuez Pecana",
            "imageUrl": "https://res.cloudinary.com/dcjdxf0kk/image/upload/v1778306770/smart-recipe-planner/ai-generated/sweet-potato-pudding-with-coconut-milk-and-vanilla-1778306770387.jpg",
            "calories": 210,
            "proteinGrams": 15,
            "carbsGrams": 14,
            "fatGrams": 10,
            "mealType": "SNACK",
            "portionMultiplier": 1,
            "selectionLogicCode": "PROTEIN_FILL",
            "aiReasoning": "Proteína láctea de lenta digestión y antioxidantes naturales.",
            "estimatedCost": 28,
            "pantryUsage": 0
        },
        {
            "recipeUUID": "aa88ee11-b21a-4ee1-bdee-11ccdd22aa88",
            "recipeName": "Agua de Jamaica con Infusión de Canela y Stevia",
            "imageUrl": "https://res.cloudinary.com/dcjdxf0kk/image/upload/v1777619350/smart-recipe-planner/ai-generated/natural-sugar-free-tamarind-agua-fresca-1777619350330.jpg",
            "calories": 10,
            "proteinGrams": 0,
            "carbsGrams": 2,
            "fatGrams": 0,
            "mealType": "SNACK",
            "portionMultiplier": 1,
            "selectionLogicCode": "PROTEIN_FILL",
            "aiReasoning": "Excelente diurético y refrescante libre de azúcar.",
            "estimatedCost": 12,
            "pantryUsage": 0
        }
    ],
    jue: [
        {
            "recipeUUID": "b11d22e3-f1a2-4fd1-a8ee-2211bb8833cc",
            "recipeName": "Hot Cakes Fit de Avena y Plátano",
            "imageUrl": "https://res.cloudinary.com/dcjdxf0kk/image/upload/v1778652475/smart-recipe-planner/ai-generated/viral-egg-and-avocado-tortilla-wrap-hack-1778652475786.jpg",
            "calories": 390,
            "proteinGrams": 14,
            "carbsGrams": 55,
            "fatGrams": 8,
            "mealType": "BREAKFAST",
            "portionMultiplier": 1,
            "selectionLogicCode": "PROTEIN_FILL",
            "aiReasoning": "Ideal para recargar glucógeno muscular con fuentes naturales de energía.",
            "estimatedCost": 22,
            "pantryUsage": 0
        },
        {
            "recipeUUID": "a22c33d4-e1d2-43bb-ac22-11ee3388bbcc",
            "recipeName": "Filete de Res Magro con Brócoli Salteado",
            "imageUrl": "https://res.cloudinary.com/dcjdxf0kk/image/upload/v1778569527/smart-recipe-planner/ai-generated/amaranth-and-honey-crusted-chicken-breast-1778569527013.jpg",
            "calories": 610,
            "proteinGrams": 48,
            "carbsGrams": 14,
            "fatGrams": 22,
            "mealType": "LUNCH",
            "portionMultiplier": 1,
            "selectionLogicCode": "PROTEIN_FILL",
            "aiReasoning": "Aporte elevado de hierro hemínico y proteína estructural de alta calidad.",
            "estimatedCost": 120,
            "pantryUsage": 0
        },
        {
            "recipeUUID": "f33dd44e-a12b-4221-a3ee-cc1122bbff00",
            "recipeName": "Sopa Tradicional de Lentejas con Verduras",
            "imageUrl": "https://res.cloudinary.com/dcjdxf0kk/image/upload/v1776924910/smart-recipe-planner/ai-generated/whole-wheat-pasta-soup-with-julienned-vegetables-1776924910828.jpg",
            "calories": 320,
            "proteinGrams": 18,
            "carbsGrams": 45,
            "fatGrams": 4,
            "mealType": "DINNER",
            "portionMultiplier": 1,
            "selectionLogicCode": "PROTEIN_FILL",
            "aiReasoning": "Proteína de origen vegetal rica en fibra dietética y potasio.",
            "estimatedCost": 25,
            "pantryUsage": 0
        },
        {
            "recipeUUID": "d44cc55e-2f3a-442d-90ab-ccdd11ee9900",
            "recipeName": "Batido de Proteína con Fresas y Leche de Almendras",
            "imageUrl": "https://res.cloudinary.com/dcjdxf0kk/image/upload/v1778306770/smart-recipe-planner/ai-generated/sweet-potato-pudding-with-coconut-milk-and-vanilla-1778306770387.jpg",
            "calories": 180,
            "proteinGrams": 24,
            "carbsGrams": 12,
            "fatGrams": 4,
            "mealType": "SNACK",
            "portionMultiplier": 1,
            "selectionLogicCode": "PROTEIN_FILL",
            "aiReasoning": "Excelente recuperación muscular post-entrenamiento.",
            "estimatedCost": 35,
            "pantryUsage": 0
        },
        {
            "recipeUUID": "e55bb66f-1d2f-45a1-a8ab-ee22dd11ee22",
            "recipeName": "Té Verde Helado con Toque de Menta Fresca",
            "imageUrl": "https://res.cloudinary.com/dcjdxf0kk/image/upload/v1777619350/smart-recipe-planner/ai-generated/natural-sugar-free-tamarind-agua-fresca-1777619350330.jpg",
            "calories": 5,
            "proteinGrams": 0,
            "carbsGrams": 1,
            "fatGrams": 0,
            "mealType": "SNACK",
            "portionMultiplier": 1,
            "selectionLogicCode": "PROTEIN_FILL",
            "aiReasoning": "Aporte concentrado de polifenoles y catequinas antioxidantes.",
            "estimatedCost": 10,
            "pantryUsage": 0
        }
    ],
    vie: [
        {
            "recipeUUID": "c11d22aa-3f2d-411a-8bbd-1e12e3e21a30",
            "recipeName": "Bowl Energético de Huevo y Quinoa",
            "imageUrl": "https://res.cloudinary.com/dcjdxf0kk/image/upload/v1778652475/smart-recipe-planner/ai-generated/viral-egg-and-avocado-tortilla-wrap-hack-1778652475786.jpg",
            "calories": 450,
            "proteinGrams": 22,
            "carbsGrams": 45,
            "fatGrams": 14,
            "mealType": "BREAKFAST",
            "portionMultiplier": 1,
            "selectionLogicCode": "PROTEIN_FILL",
            "aiReasoning": "Carbohidratos complejos de bajo índice glucémico y aminoácidos completos.",
            "estimatedCost": 40,
            "pantryUsage": 0
        },
        {
            "recipeUUID": "d22bb33f-a2b1-4cd2-b912-2c32de11eeaa",
            "recipeName": "Filete de Pescado Blanco a la Plancha con Hierbas",
            "imageUrl": "https://res.cloudinary.com/dcjdxf0kk/image/upload/v1778569527/smart-recipe-planner/ai-generated/amaranth-and-honey-crusted-chicken-breast-1778569527013.jpg",
            "calories": 480,
            "proteinGrams": 38,
            "carbsGrams": 12,
            "fatGrams": 10,
            "mealType": "LUNCH",
            "portionMultiplier": 1,
            "selectionLogicCode": "PROTEIN_FILL",
            "aiReasoning": "Comida ligera, de fácil digestión y muy baja en grasas saturadas.",
            "estimatedCost": 80,
            "pantryUsage": 0
        },
        {
            "recipeUUID": "e33cc44d-f2e2-4112-be33-ee3312abef30",
            "recipeName": "Wrap de Pavo con Queso Cottage en Tortilla de Espinaca",
            "imageUrl": "https://res.cloudinary.com/dcjdxf0kk/image/upload/v1776924910/smart-recipe-planner/ai-generated/whole-wheat-pasta-soup-with-julienned-vegetables-1776924910828.jpg",
            "calories": 340,
            "proteinGrams": 28,
            "carbsGrams": 24,
            "fatGrams": 8,
            "mealType": "DINNER",
            "portionMultiplier": 1,
            "selectionLogicCode": "PROTEIN_FILL",
            "aiReasoning": "Cena rápida de viernes, rica en triptófano para regular el sueño.",
            "estimatedCost": 45,
            "pantryUsage": 0
        },
        {
            "recipeUUID": "f44dd55d-e3d1-4112-99ab-ccee2211bb40",
            "recipeName": "Mix de Nueces con Semillas de Calabaza",
            "imageUrl": "https://res.cloudinary.com/dcjdxf0kk/image/upload/v1778306770/smart-recipe-planner/ai-generated/sweet-potato-pudding-with-coconut-milk-and-vanilla-1778306770387.jpg",
            "calories": 190,
            "proteinGrams": 7,
            "carbsGrams": 8,
            "fatGrams": 16,
            "mealType": "SNACK",
            "portionMultiplier": 1,
            "selectionLogicCode": "PROTEIN_FILL",
            "aiReasoning": "Grasas saludables y minerales (zinc, magnesio) para recargar energías.",
            "estimatedCost": 20,
            "pantryUsage": 0
        },
        {
            "recipeUUID": "a55ee66b-b21a-4ee1-bdee-11ccdd22aa44",
            "recipeName": "Limonada Natural de Hierbabuena con Chía",
            "imageUrl": "https://res.cloudinary.com/dcjdxf0kk/image/upload/v1777619350/smart-recipe-planner/ai-generated/natural-sugar-free-tamarind-agua-fresca-1777619350330.jpg",
            "calories": 45,
            "proteinGrams": 1,
            "carbsGrams": 9,
            "fatGrams": 1,
            "mealType": "SNACK",
            "portionMultiplier": 1,
            "selectionLogicCode": "PROTEIN_FILL",
            "aiReasoning": "Bebida rica en vitamina C y fibra soluble para refrescarte.",
            "estimatedCost": 15,
            "pantryUsage": 0
        }
    ],
    sab: [
        {
            "recipeUUID": "d11d22ab-f1a2-4fd1-a8ee-2211bb8833dd",
            "recipeName": "Sourdough Toast con Champiñones y Huevo Ponchado",
            "imageUrl": "https://res.cloudinary.com/dcjdxf0kk/image/upload/v1778652475/smart-recipe-planner/ai-generated/viral-egg-and-avocado-tortilla-wrap-hack-1778652475786.jpg",
            "calories": 380,
            "proteinGrams": 18,
            "carbsGrams": 36,
            "fatGrams": 12,
            "mealType": "BREAKFAST",
            "portionMultiplier": 1,
            "selectionLogicCode": "PROTEIN_FILL",
            "aiReasoning": "Carbohidratos fermentados de masa madre y proteínas de digestión óptima.",
            "estimatedCost": 50,
            "pantryUsage": 0
        },
        {
            "recipeUUID": "e22c33d5-e1d2-43bb-ac22-11ee3388bbdd",
            "recipeName": "Fajitas de Pollo Tres Colores con Pimientos",
            "imageUrl": "https://res.cloudinary.com/dcjdxf0kk/image/upload/v1778569527/smart-recipe-planner/ai-generated/amaranth-and-honey-crusted-chicken-breast-1778569527013.jpg",
            "calories": 540,
            "proteinGrams": 46,
            "carbsGrams": 22,
            "fatGrams": 14,
            "mealType": "LUNCH",
            "portionMultiplier": 1,
            "selectionLogicCode": "PROTEIN_FILL",
            "aiReasoning": "Plato alto en vitamina C y proteínas magras de alta palatabilidad.",
            "estimatedCost": 70,
            "pantryUsage": 0
        },
        {
            "recipeUUID": "f33dd44f-a12b-4221-a3ee-cc1122bbff11",
            "recipeName": "Caldo de Pollo Casero con Verduras de la Estación",
            "imageUrl": "https://res.cloudinary.com/dcjdxf0kk/image/upload/v1776924910/smart-recipe-planner/ai-generated/whole-wheat-pasta-soup-with-julienned-vegetables-1776924910828.jpg",
            "calories": 290,
            "proteinGrams": 24,
            "carbsGrams": 18,
            "fatGrams": 6,
            "mealType": "DINNER",
            "portionMultiplier": 1,
            "selectionLogicCode": "PROTEIN_FILL",
            "aiReasoning": "Cena ultra ligera y fácil de digerir para reparar el organismo.",
            "estimatedCost": 35,
            "pantryUsage": 0
        },
        {
            "recipeUUID": "a44cc55f-2f3a-442d-90ab-ccdd11ee9911",
            "recipeName": "Rodajas de Manzana con Mantequilla de Maní Natural",
            "imageUrl": "https://res.cloudinary.com/dcjdxf0kk/image/upload/v1778306770/smart-recipe-planner/ai-generated/sweet-potato-pudding-with-coconut-milk-and-vanilla-1778306770387.jpg",
            "calories": 240,
            "proteinGrams": 7,
            "carbsGrams": 24,
            "fatGrams": 14,
            "mealType": "SNACK",
            "portionMultiplier": 1,
            "selectionLogicCode": "PROTEIN_FILL",
            "aiReasoning": "Aporte energético de grasas monoinsaturadas y fibra de la fruta.",
            "estimatedCost": 18,
            "pantryUsage": 0
        },
        {
            "recipeUUID": "b55bb66g-1d2f-45a1-a8ab-ee22dd11ee33",
            "recipeName": "Agua de Horchata de Arroz Integral Light",
            "imageUrl": "https://res.cloudinary.com/dcjdxf0kk/image/upload/v1777619350/smart-recipe-planner/ai-generated/natural-sugar-free-tamarind-agua-fresca-1777619350330.jpg",
            "calories": 75,
            "proteinGrams": 1,
            "carbsGrams": 16,
            "fatGrams": 0,
            "mealType": "SNACK",
            "portionMultiplier": 1,
            "selectionLogicCode": "PROTEIN_FILL",
            "aiReasoning": "Bebida refrescante elaborada con arroz integral y canela.",
            "estimatedCost": 12,
            "pantryUsage": 0
        }
    ],
    dom: [
        {
            "recipeUUID": "e11d22ac-3f2d-411a-8bbd-1e12e3e21a40",
            "recipeName": "Shakshuka de la Casa (Huevos en Salsa de Tomate y Especias)",
            "imageUrl": "https://res.cloudinary.com/dcjdxf0kk/image/upload/v1778652475/smart-recipe-planner/ai-generated/viral-egg-and-avocado-tortilla-wrap-hack-1778652475786.jpg",
            "calories": 410,
            "proteinGrams": 20,
            "carbsGrams": 22,
            "fatGrams": 18,
            "mealType": "BREAKFAST",
            "portionMultiplier": 1,
            "selectionLogicCode": "PROTEIN_FILL",
            "aiReasoning": "Desayuno tradicional de fin de semana con licopenos del tomate.",
            "estimatedCost": 40,
            "pantryUsage": 0
        },
        {
            "recipeUUID": "f22bb33g-a2b1-4cd2-b912-2c32de11eebb",
            "recipeName": "Brochetas de Ternera y Pimientos al Carbón",
            "imageUrl": "https://res.cloudinary.com/dcjdxf0kk/image/upload/v1778569527/smart-recipe-planner/ai-generated/amaranth-and-honey-crusted-chicken-breast-1778569527013.jpg",
            "calories": 580,
            "proteinGrams": 44,
            "carbsGrams": 18,
            "fatGrams": 24,
            "mealType": "LUNCH",
            "portionMultiplier": 1,
            "selectionLogicCode": "PROTEIN_FILL",
            "aiReasoning": "Excelente fuente de hierro y aminoácidos para el fin de semana.",
            "estimatedCost": 90,
            "pantryUsage": 0
        },
        {
            "recipeUUID": "a33cc44e-f2e2-4112-be33-ee3312abef40",
            "recipeName": "Ensalada Templada de Quinoa y Calabaza",
            "imageUrl": "https://res.cloudinary.com/dcjdxf0kk/image/upload/v1776924910/smart-recipe-planner/ai-generated/whole-wheat-pasta-soup-with-julienned-vegetables-1776924910828.jpg",
            "calories": 360,
            "proteinGrams": 12,
            "carbsGrams": 48,
            "fatGrams": 10,
            "mealType": "DINNER",
            "portionMultiplier": 1,
            "selectionLogicCode": "PROTEIN_FILL",
            "aiReasoning": "Quinoa integral y carbohidratos complejos de fácil asimilación.",
            "estimatedCost": 35,
            "pantryUsage": 0
        },
        {
            "recipeUUID": "b44dd55e-e3d1-4112-99ab-ccee2211bb45",
            "recipeName": "Pudín de Chía con Puré de Mango Orgánico",
            "imageUrl": "https://res.cloudinary.com/dcjdxf0kk/image/upload/v1778306770/smart-recipe-planner/ai-generated/sweet-potato-pudding-with-coconut-milk-and-vanilla-1778306770387.jpg",
            "calories": 220,
            "proteinGrams": 6,
            "carbsGrams": 28,
            "fatGrams": 8,
            "mealType": "SNACK",
            "portionMultiplier": 1,
            "selectionLogicCode": "PROTEIN_FILL",
            "aiReasoning": "Alto contenido de omega-3 de origen vegetal y fibra soluble.",
            "estimatedCost": 22,
            "pantryUsage": 0
        },
        {
            "recipeUUID": "c55ee66c-b21a-4ee1-bdee-11ccdd22aa55",
            "recipeName": "Licuado Frío de Matcha y Leche de Coco",
            "imageUrl": "https://res.cloudinary.com/dcjdxf0kk/image/upload/v1777619350/smart-recipe-planner/ai-generated/natural-sugar-free-tamarind-agua-fresca-1777619350330.jpg",
            "calories": 90,
            "proteinGrams": 2,
            "carbsGrams": 12,
            "fatGrams": 4,
            "mealType": "SNACK",
            "portionMultiplier": 1,
            "selectionLogicCode": "PROTEIN_FILL",
            "aiReasoning": "Matcha de grado ceremonial rico en L-teanina para inducir calma.",
            "estimatedCost": 25,
            "pantryUsage": 0
        }
    ]
};

// Fallback for daily backward-compatibility
export const RECOMMENDED_DAILY_MENU: RecommendedMeal[] = RECOMMENDED_WEEKLY_MENU.lun;